# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u9508/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/u9508/proprietary/system/bin/glgps:system/bin/glgps \
    vendor/huawei/u9508/proprietary/system/bin/rild:system/bin/rild \
    vendor/huawei/u9508/proprietary/system/bin/akmd8963:system/bin/akmd8963 \
    vendor/huawei/u9508/proprietary/system/bin/gpslogd:system/bin/gpslogd \
    vendor/huawei/u9508/proprietary/system/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/huawei/u9508/proprietary/system/bin/hci_dev_state:system/bin/hci_dev_state \
    vendor/huawei/u9508/proprietary/etc/bluetooth/BCM4330.hcd:etc/bluetooth/BCM4330.hcd \
    vendor/huawei/u9508/proprietary/system/lib/libRedEye.so:system/lib/libRedEye.so \
    vendor/huawei/u9508/proprietary/system/lib/libril.so:system/lib/libril.so \
    vendor/huawei/u9508/proprietary/system/lib/libxgold-ril.so:system/lib/libxgold-ril.so \
    vendor/huawei/u9508/proprietary/system/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/huawei/u9508/proprietary/system/lib/libchip_management.so:system/lib/libchip_management.so \
    vendor/huawei/u9508/proprietary/system/lib/libbluedroid.so:system/lib/libbluedroid.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_asf_extractor.so:system/lib/lib_k3_asf_extractor.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_avi_extractor.so:system/lib/lib_k3_avi_extractor.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_extractor_utils.so:system/lib/lib_k3_extractor_utils.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_flv_extractor.so:system/lib/lib_k3_flv_extractor.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_generic_audio_extractor.so:system/lib/lib_k3_generic_audio_extractor.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_m2ts_extractor.so:system/lib/lib_k3_m2ts_extractor.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_mov_extractor.so:system/lib/lib_k3_mov_extractor.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_mpg_extractor.so:system/lib/lib_k3_mpg_extractor.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_omx_avc.so:system/lib/lib_k3_omx_avc.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_omx_avcenc.so:system/lib/lib_k3_omx_avcenc.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_omx_mpeg2.so:system/lib/lib_k3_omx_mpeg2.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_omx_mpeg4.so:system/lib/lib_k3_omx_mpeg4.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_omx_rv.so:system/lib/lib_k3_omx_rv.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_omx_vc1.so:system/lib/lib_k3_omx_vc1.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_omx_vp8.so:system/lib/lib_k3_omx_vp8.so \
    vendor/huawei/u9508/proprietary/system/lib/lib_k3_omxcore.so:system/lib/lib_k3_omxcore.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/audio.primary.k3v2oem1.so:system/lib/hw/audio.primary.k3v2oem1.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/audio_policy.k3v2oem1.so:system/lib/hw/audio_policy.k3v2oem1.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/camera.k3v2oem1.so:system/lib/hw/camera.k3v2oem1.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/copybit.huawei.so:system/lib/hw/copybit.huawei.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/gps.k3v2oem1.so:system/lib/hw/gps.k3v2oem1.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/gralloc.huawei.so:system/lib/hw/gralloc.huawei.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/hwcomposer.huawei.so:system/lib/hw/hwcomposer.huawei.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/libbcmfm_if.so:system/lib/hw/libbcmfm_if.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/power.default.so:system/lib/hw/power.default.so \
    vendor/huawei/u9508/proprietary/system/lib/hw/sensors.k3v2oem1.so:system/lib/hw/sensors.k3v2oem1.so \
    vendor/huawei/u9508/proprietary/system/lib/egl/libEGL_VIVANTE.so:system/lib/egl/libEGL_VIVANTE.so \
    vendor/huawei/u9508/proprietary/system/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/huawei/u9508/proprietary/system/lib/egl/libGLESv1_CM_VIVANTE.so:system/lib/egl/libGLESv1_CM_VIVANTE.so \
    vendor/huawei/u9508/proprietary/system/lib/egl/libGLESv2_VIVANTE.so:system/lib/egl/libGLESv2_VIVANTE.so \
    vendor/huawei/u9508/proprietary/vendor/firmware/fw_bcmdhd.bin:vendor/firmware/fw_bcmdhd.bin \
    vendor/huawei/u9508/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:vendor/firmware/fw_bcmdhd_apsta.bin \
    vendor/huawei/u9508/proprietary/vendor/firmware/fw_bcmdhd_p2p.bin:vendor/firmware/fw_bcmdhd_p2p.bin \
    vendor/huawei/u9508/proprietary/vendor/firmware/fw_bcmdhd_test.bin:vendor/firmware/fw_bcmdhd_test.bin \
    vendor/huawei/u9508/proprietary/vendor/firmware/nvram.txt:vendor/firmware/nvram.txt \
    vendor/huawei/u9508/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/huawei/u9508/proprietary/vendor/lib/libwvdrm_L3.so:vendor/lib/libwvdrm_L3.so \
    vendor/huawei/u9508/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin:vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin \
    vendor/huawei/u9508/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin:vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin \
    vendor/huawei/u9508/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2/full_model.bin:vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2/full_model.bin \
    vendor/huawei/u9508/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24/full_model.bin:vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24/full_model.bin \
    vendor/huawei/u9508/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24/full_model.bin:vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24/full_model.bin \
    vendor/huawei/u9508/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24/full_model.bin:vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24/full_model.bin \
    vendor/huawei/u9508/proprietary/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin:system/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin
